import React from 'react';
import { DataProvider } from './context/DataContext';
import { Providers } from "./providers";


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
          <DataProvider>
            <body>{children}</body>
          </DataProvider>        
      </body>
    </html>
  )
}
