import React from 'react';
import { DataProvider } from './context/DataContext';
// import { Providers } from "./providers";
import '../globals.css';
import main from './template'


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
              <main>
              <DataProvider>
                {children}
              </DataProvider>   
              </main>          
      </body>
    </html>
  )
}
